// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/lbrlabs/pulumi-launchdarkly/sdk/go/launchdarkly/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// The [personal access token](https://docs.launchdarkly.com/home/account-security/api-access-tokens#personal-tokens) or [service token](https://docs.launchdarkly.com/home/account-security/api-access-tokens#service-tokens) used to authenticate with LaunchDarkly. You can also set this with the `LAUNCHDARKLY_ACCESS_TOKEN` environment variable. You must provide either `accessToken` or `oauthToken`.
func GetAccessToken(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "launchdarkly:accessToken")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault(nil, nil, "LAUNCHDARKLY_ACCESS_TOKEN"); d != nil {
		value = d.(string)
	}
	return value
}

// The LaunchDarkly host address. If this argument is not specified, the default host address is `https://app.launchdarkly.com`
func GetApiHost(ctx *pulumi.Context) string {
	return config.Get(ctx, "launchdarkly:apiHost")
}

// The HTTP timeout (in seconds) when making API calls to LaunchDarkly. Defaults to 20 seconds.
func GetHttpTimeout(ctx *pulumi.Context) int {
	return config.GetInt(ctx, "launchdarkly:httpTimeout")
}

// An OAuth V2 token you use to authenticate with LaunchDarkly. You can also set this with the `LAUNCHDARKLY_OAUTH_TOKEN` environment variable. You must provide either `accessToken` or `oauthToken`.
func GetOauthToken(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "launchdarkly:oauthToken")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault(nil, nil, "LAUNCHDARKLY_OAUTH_TOKEN"); d != nil {
		value = d.(string)
	}
	return value
}
