linters:
  enable:
    - errcheck
    - goconst
    - gofmt
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - unconvert
    - unused
    - staticcheck
  enable-all: false
run:
  timeout: 20m
