// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Launchdarkly.Outputs
{

    [OutputType]
    public sealed class GetFeatureFlagVariationResult
    {
        /// <summary>
        /// The variation's description.
        /// </summary>
        public readonly string? Description;
        /// <summary>
        /// The name of the variation.
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// The variation value. The value's type must correspond to the `VariationType` argument. For example: `VariationType = "boolean"` accepts only `True` or `False`. The `Number` variation type accepts both floats and ints, but please note that any trailing zeroes on floats will be trimmed (i.e. `1.1` and `1.100` will both be converted to `1.1`).
        /// 
        /// If you wish to define an empty string variation, you must still define the value field on the variations block like so:
        /// 
        /// ```terraform
        /// variations {
        ///   value = ""
        /// }
        /// ```
        /// 
        /// &gt; **Note:** Terraform manages `Variations` as an ordered array and identifies them by index. This means that if you change the order of your `Variations` block, you may end up destroying and recreating those variations. Additionally, if you delete variations that have targets that have been attached outside of Terraform, those targets may be incorrectly reassigned to a different variation.
        /// </summary>
        public readonly string Value;

        [OutputConstructor]
        private GetFeatureFlagVariationResult(
            string? description,

            string? name,

            string value)
        {
            Description = description;
            Name = name;
            Value = value;
        }
    }
}
