// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Launchdarkly
{
    /// <summary>
    /// Provides a LaunchDarkly environment-specific feature flag resource.
    /// 
    /// This resource allows you to create and manage environment-specific feature flags attributes within your LaunchDarkly organization.
    /// 
    /// &gt; **Note:** If you intend to attach a feature flag to any experiments, we do _not_ recommend configuring environment-specific flag settings using Terraform. Subsequent applies may overwrite the changes made by experiments and break your experiment. An alternate workaround is to use the lifecycle.ignore_changes Terraform meta-argument on the `Fallthrough` field to prevent potential overwrites.
    /// 
    /// ## Example Usage
    /// 
    /// ## Import
    /// 
    /// LaunchDarkly feature flag environments can be imported using the resource's ID in the form `project_key/env_key/flag_key`
    /// 
    /// ```sh
    /// $ pulumi import launchdarkly:index/featureFlagEnvironment:FeatureFlagEnvironment example example-project/example-env/example-flag-key
    /// ```
    /// </summary>
    [LaunchdarklyResourceType("launchdarkly:index/featureFlagEnvironment:FeatureFlagEnvironment")]
    public partial class FeatureFlagEnvironment : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The set of nested blocks describing the individual targets for non-user context kinds for each variation.
        /// </summary>
        [Output("contextTargets")]
        public Output<ImmutableArray<Outputs.FeatureFlagEnvironmentContextTarget>> ContextTargets { get; private set; } = null!;

        /// <summary>
        /// The environment key. A change in this field will force the destruction of the existing resource and the creation of a new one.
        /// </summary>
        [Output("envKey")]
        public Output<string> EnvKey { get; private set; } = null!;

        /// <summary>
        /// Nested block describing the default variation to serve if no `Prerequisites`, `Target`, or `Rules` apply.
        /// </summary>
        [Output("fallthrough")]
        public Output<Outputs.FeatureFlagEnvironmentFallthrough> Fallthrough { get; private set; } = null!;

        /// <summary>
        /// The feature flag's unique `Id` in the format `project_key/flag_key`. A change in this field will force the destruction of the existing resource and the creation of a new one.
        /// </summary>
        [Output("flagId")]
        public Output<string> FlagId { get; private set; } = null!;

        /// <summary>
        /// The index of the variation to serve if targeting is disabled.
        /// </summary>
        [Output("offVariation")]
        public Output<int> OffVariation { get; private set; } = null!;

        /// <summary>
        /// Whether targeting is enabled. Defaults to `False` if not set.
        /// </summary>
        [Output("on")]
        public Output<bool?> On { get; private set; } = null!;

        /// <summary>
        /// List of nested blocks describing prerequisite feature flags rules.
        /// </summary>
        [Output("prerequisites")]
        public Output<ImmutableArray<Outputs.FeatureFlagEnvironmentPrerequisite>> Prerequisites { get; private set; } = null!;

        /// <summary>
        /// List of logical targeting rules.
        /// </summary>
        [Output("rules")]
        public Output<ImmutableArray<Outputs.FeatureFlagEnvironmentRule>> Rules { get; private set; } = null!;

        /// <summary>
        /// Set of nested blocks describing the individual user targets for each variation.
        /// </summary>
        [Output("targets")]
        public Output<ImmutableArray<Outputs.FeatureFlagEnvironmentTarget>> Targets { get; private set; } = null!;

        /// <summary>
        /// Whether to send event data back to LaunchDarkly. Defaults to `False` if not set.
        /// </summary>
        [Output("trackEvents")]
        public Output<bool?> TrackEvents { get; private set; } = null!;


        /// <summary>
        /// Create a FeatureFlagEnvironment resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public FeatureFlagEnvironment(string name, FeatureFlagEnvironmentArgs args, CustomResourceOptions? options = null)
            : base("launchdarkly:index/featureFlagEnvironment:FeatureFlagEnvironment", name, args ?? new FeatureFlagEnvironmentArgs(), MakeResourceOptions(options, ""))
        {
        }

        private FeatureFlagEnvironment(string name, Input<string> id, FeatureFlagEnvironmentState? state = null, CustomResourceOptions? options = null)
            : base("launchdarkly:index/featureFlagEnvironment:FeatureFlagEnvironment", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/lbrlabs",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing FeatureFlagEnvironment resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static FeatureFlagEnvironment Get(string name, Input<string> id, FeatureFlagEnvironmentState? state = null, CustomResourceOptions? options = null)
        {
            return new FeatureFlagEnvironment(name, id, state, options);
        }
    }

    public sealed class FeatureFlagEnvironmentArgs : global::Pulumi.ResourceArgs
    {
        [Input("contextTargets")]
        private InputList<Inputs.FeatureFlagEnvironmentContextTargetArgs>? _contextTargets;

        /// <summary>
        /// The set of nested blocks describing the individual targets for non-user context kinds for each variation.
        /// </summary>
        public InputList<Inputs.FeatureFlagEnvironmentContextTargetArgs> ContextTargets
        {
            get => _contextTargets ?? (_contextTargets = new InputList<Inputs.FeatureFlagEnvironmentContextTargetArgs>());
            set => _contextTargets = value;
        }

        /// <summary>
        /// The environment key. A change in this field will force the destruction of the existing resource and the creation of a new one.
        /// </summary>
        [Input("envKey", required: true)]
        public Input<string> EnvKey { get; set; } = null!;

        /// <summary>
        /// Nested block describing the default variation to serve if no `Prerequisites`, `Target`, or `Rules` apply.
        /// </summary>
        [Input("fallthrough", required: true)]
        public Input<Inputs.FeatureFlagEnvironmentFallthroughArgs> Fallthrough { get; set; } = null!;

        /// <summary>
        /// The feature flag's unique `Id` in the format `project_key/flag_key`. A change in this field will force the destruction of the existing resource and the creation of a new one.
        /// </summary>
        [Input("flagId", required: true)]
        public Input<string> FlagId { get; set; } = null!;

        /// <summary>
        /// The index of the variation to serve if targeting is disabled.
        /// </summary>
        [Input("offVariation", required: true)]
        public Input<int> OffVariation { get; set; } = null!;

        /// <summary>
        /// Whether targeting is enabled. Defaults to `False` if not set.
        /// </summary>
        [Input("on")]
        public Input<bool>? On { get; set; }

        [Input("prerequisites")]
        private InputList<Inputs.FeatureFlagEnvironmentPrerequisiteArgs>? _prerequisites;

        /// <summary>
        /// List of nested blocks describing prerequisite feature flags rules.
        /// </summary>
        public InputList<Inputs.FeatureFlagEnvironmentPrerequisiteArgs> Prerequisites
        {
            get => _prerequisites ?? (_prerequisites = new InputList<Inputs.FeatureFlagEnvironmentPrerequisiteArgs>());
            set => _prerequisites = value;
        }

        [Input("rules")]
        private InputList<Inputs.FeatureFlagEnvironmentRuleArgs>? _rules;

        /// <summary>
        /// List of logical targeting rules.
        /// </summary>
        public InputList<Inputs.FeatureFlagEnvironmentRuleArgs> Rules
        {
            get => _rules ?? (_rules = new InputList<Inputs.FeatureFlagEnvironmentRuleArgs>());
            set => _rules = value;
        }

        [Input("targets")]
        private InputList<Inputs.FeatureFlagEnvironmentTargetArgs>? _targets;

        /// <summary>
        /// Set of nested blocks describing the individual user targets for each variation.
        /// </summary>
        public InputList<Inputs.FeatureFlagEnvironmentTargetArgs> Targets
        {
            get => _targets ?? (_targets = new InputList<Inputs.FeatureFlagEnvironmentTargetArgs>());
            set => _targets = value;
        }

        /// <summary>
        /// Whether to send event data back to LaunchDarkly. Defaults to `False` if not set.
        /// </summary>
        [Input("trackEvents")]
        public Input<bool>? TrackEvents { get; set; }

        public FeatureFlagEnvironmentArgs()
        {
        }
        public static new FeatureFlagEnvironmentArgs Empty => new FeatureFlagEnvironmentArgs();
    }

    public sealed class FeatureFlagEnvironmentState : global::Pulumi.ResourceArgs
    {
        [Input("contextTargets")]
        private InputList<Inputs.FeatureFlagEnvironmentContextTargetGetArgs>? _contextTargets;

        /// <summary>
        /// The set of nested blocks describing the individual targets for non-user context kinds for each variation.
        /// </summary>
        public InputList<Inputs.FeatureFlagEnvironmentContextTargetGetArgs> ContextTargets
        {
            get => _contextTargets ?? (_contextTargets = new InputList<Inputs.FeatureFlagEnvironmentContextTargetGetArgs>());
            set => _contextTargets = value;
        }

        /// <summary>
        /// The environment key. A change in this field will force the destruction of the existing resource and the creation of a new one.
        /// </summary>
        [Input("envKey")]
        public Input<string>? EnvKey { get; set; }

        /// <summary>
        /// Nested block describing the default variation to serve if no `Prerequisites`, `Target`, or `Rules` apply.
        /// </summary>
        [Input("fallthrough")]
        public Input<Inputs.FeatureFlagEnvironmentFallthroughGetArgs>? Fallthrough { get; set; }

        /// <summary>
        /// The feature flag's unique `Id` in the format `project_key/flag_key`. A change in this field will force the destruction of the existing resource and the creation of a new one.
        /// </summary>
        [Input("flagId")]
        public Input<string>? FlagId { get; set; }

        /// <summary>
        /// The index of the variation to serve if targeting is disabled.
        /// </summary>
        [Input("offVariation")]
        public Input<int>? OffVariation { get; set; }

        /// <summary>
        /// Whether targeting is enabled. Defaults to `False` if not set.
        /// </summary>
        [Input("on")]
        public Input<bool>? On { get; set; }

        [Input("prerequisites")]
        private InputList<Inputs.FeatureFlagEnvironmentPrerequisiteGetArgs>? _prerequisites;

        /// <summary>
        /// List of nested blocks describing prerequisite feature flags rules.
        /// </summary>
        public InputList<Inputs.FeatureFlagEnvironmentPrerequisiteGetArgs> Prerequisites
        {
            get => _prerequisites ?? (_prerequisites = new InputList<Inputs.FeatureFlagEnvironmentPrerequisiteGetArgs>());
            set => _prerequisites = value;
        }

        [Input("rules")]
        private InputList<Inputs.FeatureFlagEnvironmentRuleGetArgs>? _rules;

        /// <summary>
        /// List of logical targeting rules.
        /// </summary>
        public InputList<Inputs.FeatureFlagEnvironmentRuleGetArgs> Rules
        {
            get => _rules ?? (_rules = new InputList<Inputs.FeatureFlagEnvironmentRuleGetArgs>());
            set => _rules = value;
        }

        [Input("targets")]
        private InputList<Inputs.FeatureFlagEnvironmentTargetGetArgs>? _targets;

        /// <summary>
        /// Set of nested blocks describing the individual user targets for each variation.
        /// </summary>
        public InputList<Inputs.FeatureFlagEnvironmentTargetGetArgs> Targets
        {
            get => _targets ?? (_targets = new InputList<Inputs.FeatureFlagEnvironmentTargetGetArgs>());
            set => _targets = value;
        }

        /// <summary>
        /// Whether to send event data back to LaunchDarkly. Defaults to `False` if not set.
        /// </summary>
        [Input("trackEvents")]
        public Input<bool>? TrackEvents { get; set; }

        public FeatureFlagEnvironmentState()
        {
        }
        public static new FeatureFlagEnvironmentState Empty => new FeatureFlagEnvironmentState();
    }
}
