// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Launchdarkly
{
    public static class GetView
    {
        /// <summary>
        /// Provides a LaunchDarkly view data source.
        /// 
        /// This data source allows you to retrieve view information from your LaunchDarkly project.
        /// 
        /// ## Example Usage
        /// 
        /// ```terraform
        /// # Example: Get view information including linked flags
        /// data "launchdarkly_view" "example" {
        ///   project_key = "example-project"
        ///   key         = "example-view"
        /// }
        /// 
        /// # The view data source now includes discovery of linked flags
        /// output "view_details" {
        ///   value = {
        ///     name         = data.launchdarkly_view.example.name
        ///     description  = data.launchdarkly_view.example.description
        ///     linked_flags = data.launchdarkly_view.example.linked_flags
        ///     maintainer   = data.launchdarkly_view.example.maintainer_id
        ///   }
        /// }
        /// 
        /// # Example: Use linked flags in conditional logic
        /// locals {
        ///   frontend_flags = contains(data.launchdarkly_view.example.linked_flags, "feature-frontend-redesign")
        ///   has_experimental_flags = length([
        ///     for flag in data.launchdarkly_view.example.linked_flags : flag
        ///     if can(regex("^experimental-", flag))
        ///   ]) &gt; 0
        /// }
        /// 
        /// # Example: Discover view membership for team access
        /// data "launchdarkly_view" "team_view" {
        ///   project_key = "my-project"
        ///   key         = "frontend-team"
        /// }
        /// 
        /// output "team_flag_access" {
        ///   description = "Flags accessible to the frontend team"
        ///   value = {
        ///     view_name  = data.launchdarkly_view.team_view.name
        ///     flag_count = length(data.launchdarkly_view.team_view.linked_flags)
        ///     flags      = data.launchdarkly_view.team_view.linked_flags
        ///   }
        /// }
        /// ```
        /// </summary>
        public static Task<GetViewResult> InvokeAsync(GetViewArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetViewResult>("launchdarkly:index/getView:getView", args ?? new GetViewArgs(), options.WithDefaults());

        /// <summary>
        /// Provides a LaunchDarkly view data source.
        /// 
        /// This data source allows you to retrieve view information from your LaunchDarkly project.
        /// 
        /// ## Example Usage
        /// 
        /// ```terraform
        /// # Example: Get view information including linked flags
        /// data "launchdarkly_view" "example" {
        ///   project_key = "example-project"
        ///   key         = "example-view"
        /// }
        /// 
        /// # The view data source now includes discovery of linked flags
        /// output "view_details" {
        ///   value = {
        ///     name         = data.launchdarkly_view.example.name
        ///     description  = data.launchdarkly_view.example.description
        ///     linked_flags = data.launchdarkly_view.example.linked_flags
        ///     maintainer   = data.launchdarkly_view.example.maintainer_id
        ///   }
        /// }
        /// 
        /// # Example: Use linked flags in conditional logic
        /// locals {
        ///   frontend_flags = contains(data.launchdarkly_view.example.linked_flags, "feature-frontend-redesign")
        ///   has_experimental_flags = length([
        ///     for flag in data.launchdarkly_view.example.linked_flags : flag
        ///     if can(regex("^experimental-", flag))
        ///   ]) &gt; 0
        /// }
        /// 
        /// # Example: Discover view membership for team access
        /// data "launchdarkly_view" "team_view" {
        ///   project_key = "my-project"
        ///   key         = "frontend-team"
        /// }
        /// 
        /// output "team_flag_access" {
        ///   description = "Flags accessible to the frontend team"
        ///   value = {
        ///     view_name  = data.launchdarkly_view.team_view.name
        ///     flag_count = length(data.launchdarkly_view.team_view.linked_flags)
        ///     flags      = data.launchdarkly_view.team_view.linked_flags
        ///   }
        /// }
        /// ```
        /// </summary>
        public static Output<GetViewResult> Invoke(GetViewInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetViewResult>("launchdarkly:index/getView:getView", args ?? new GetViewInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Provides a LaunchDarkly view data source.
        /// 
        /// This data source allows you to retrieve view information from your LaunchDarkly project.
        /// 
        /// ## Example Usage
        /// 
        /// ```terraform
        /// # Example: Get view information including linked flags
        /// data "launchdarkly_view" "example" {
        ///   project_key = "example-project"
        ///   key         = "example-view"
        /// }
        /// 
        /// # The view data source now includes discovery of linked flags
        /// output "view_details" {
        ///   value = {
        ///     name         = data.launchdarkly_view.example.name
        ///     description  = data.launchdarkly_view.example.description
        ///     linked_flags = data.launchdarkly_view.example.linked_flags
        ///     maintainer   = data.launchdarkly_view.example.maintainer_id
        ///   }
        /// }
        /// 
        /// # Example: Use linked flags in conditional logic
        /// locals {
        ///   frontend_flags = contains(data.launchdarkly_view.example.linked_flags, "feature-frontend-redesign")
        ///   has_experimental_flags = length([
        ///     for flag in data.launchdarkly_view.example.linked_flags : flag
        ///     if can(regex("^experimental-", flag))
        ///   ]) &gt; 0
        /// }
        /// 
        /// # Example: Discover view membership for team access
        /// data "launchdarkly_view" "team_view" {
        ///   project_key = "my-project"
        ///   key         = "frontend-team"
        /// }
        /// 
        /// output "team_flag_access" {
        ///   description = "Flags accessible to the frontend team"
        ///   value = {
        ///     view_name  = data.launchdarkly_view.team_view.name
        ///     flag_count = length(data.launchdarkly_view.team_view.linked_flags)
        ///     flags      = data.launchdarkly_view.team_view.linked_flags
        ///   }
        /// }
        /// ```
        /// </summary>
        public static Output<GetViewResult> Invoke(GetViewInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetViewResult>("launchdarkly:index/getView:getView", args ?? new GetViewInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetViewArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The view's unique key.
        /// </summary>
        [Input("key", required: true)]
        public string Key { get; set; } = null!;

        /// <summary>
        /// The project key.
        /// </summary>
        [Input("projectKey", required: true)]
        public string ProjectKey { get; set; } = null!;

        public GetViewArgs()
        {
        }
        public static new GetViewArgs Empty => new GetViewArgs();
    }

    public sealed class GetViewInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The view's unique key.
        /// </summary>
        [Input("key", required: true)]
        public Input<string> Key { get; set; } = null!;

        /// <summary>
        /// The project key.
        /// </summary>
        [Input("projectKey", required: true)]
        public Input<string> ProjectKey { get; set; } = null!;

        public GetViewInvokeArgs()
        {
        }
        public static new GetViewInvokeArgs Empty => new GetViewInvokeArgs();
    }


    [OutputType]
    public sealed class GetViewResult
    {
        /// <summary>
        /// Whether the view is archived.
        /// </summary>
        public readonly bool Archived;
        /// <summary>
        /// The view's description.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// Whether SDK keys are generated for this view.
        /// </summary>
        public readonly bool GenerateSdkKeys;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The view's unique key.
        /// </summary>
        public readonly string Key;
        /// <summary>
        /// A list of feature flag keys that are linked to this view.
        /// </summary>
        public readonly ImmutableArray<string> LinkedFlags;
        /// <summary>
        /// A list of segments that are linked to this view.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetViewLinkedSegmentResult> LinkedSegments;
        /// <summary>
        /// The member ID of the maintainer for this view.
        /// </summary>
        public readonly string MaintainerId;
        /// <summary>
        /// The team key of the maintainer team for this view.
        /// </summary>
        public readonly string MaintainerTeamKey;
        /// <summary>
        /// The view's name.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The project key.
        /// </summary>
        public readonly string ProjectKey;
        /// <summary>
        /// Tags associated with your resource.
        /// </summary>
        public readonly ImmutableArray<string> Tags;

        [OutputConstructor]
        private GetViewResult(
            bool archived,

            string description,

            bool generateSdkKeys,

            string id,

            string key,

            ImmutableArray<string> linkedFlags,

            ImmutableArray<Outputs.GetViewLinkedSegmentResult> linkedSegments,

            string maintainerId,

            string maintainerTeamKey,

            string name,

            string projectKey,

            ImmutableArray<string> tags)
        {
            Archived = archived;
            Description = description;
            GenerateSdkKeys = generateSdkKeys;
            Id = id;
            Key = key;
            LinkedFlags = linkedFlags;
            LinkedSegments = linkedSegments;
            MaintainerId = maintainerId;
            MaintainerTeamKey = maintainerTeamKey;
            Name = name;
            ProjectKey = projectKey;
            Tags = tags;
        }
    }
}
