// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Launchdarkly
{
    /// <summary>
    /// Provides a LaunchDarkly view links resource for managing bulk resource linkage to views.
    /// 
    /// This resource allows you to efficiently link multiple flags and/or segments to a specific view. This is particularly useful for administrators organizing resources by team or deployment unit.
    /// 
    /// &gt; **Note:** This resource manages ALL links for the specified resource types within a view. Adding or removing items from the configuration will link or unlink those resources accordingly.
    /// 
    /// ## Alternative Approach: ViewKeys on Individual Resources
    /// 
    /// For modular Terraform configurations where flags and segments are defined in separate files or modules, you can use the `ViewKeys` field directly on the resource instead of using this centralized `ViewLinks` resource:
    /// 
    /// - **Feature Flags**: Use the `ViewKeys` attribute on `launchdarkly.FeatureFlag` resources
    /// - **Segments**: Use the `ViewKeys` attribute on `launchdarkly.Segment` resources
    /// 
    /// **When to use `ViewLinks` (this resource):**
    /// - Managing many flags/segments for a single view (bulk operations)
    /// - Centralized view management across your infrastructure
    /// - Administrative view organization
    /// 
    /// **When to use `ViewKeys` on individual resources:**
    /// - Modular Terraform structures with separate files per flag/segment
    /// - Each team/module manages their own resources
    /// - Want view membership defined alongside the resource
    /// 
    /// &gt; **Warning:** Do not use both `ViewLinks` and `ViewKeys` to manage the same flag or segment's view associations. Mixed ownership can cause conflicts; when detected, Terraform logs a warning and reconciles to the managing resource's configured associations. Choose one approach per resource.
    /// 
    /// See the feature flag resource documentation and segment resource documentation for details on the `ViewKeys` attribute.
    /// 
    /// ## Example Usage
    /// </summary>
    [LaunchdarklyResourceType("launchdarkly:index/viewLinks:ViewLinks")]
    public partial class ViewLinks : global::Pulumi.CustomResource
    {
        /// <summary>
        /// A set of feature flag keys to link to the view.
        /// </summary>
        [Output("flags")]
        public Output<ImmutableArray<string>> Flags { get; private set; } = null!;

        /// <summary>
        /// The project key. A change in this field will force the destruction of the existing resource and the creation of a new one.
        /// </summary>
        [Output("projectKey")]
        public Output<string> ProjectKey { get; private set; } = null!;

        /// <summary>
        /// A set of segments to link to the view. Each segment is identified by its environment ID and segment key.
        /// </summary>
        [Output("segments")]
        public Output<ImmutableArray<Outputs.ViewLinksSegment>> Segments { get; private set; } = null!;

        /// <summary>
        /// The view key to link resources to. A change in this field will force the destruction of the existing resource and the creation of a new one.
        /// </summary>
        [Output("viewKey")]
        public Output<string> ViewKey { get; private set; } = null!;


        /// <summary>
        /// Create a ViewLinks resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ViewLinks(string name, ViewLinksArgs args, CustomResourceOptions? options = null)
            : base("launchdarkly:index/viewLinks:ViewLinks", name, args ?? new ViewLinksArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ViewLinks(string name, Input<string> id, ViewLinksState? state = null, CustomResourceOptions? options = null)
            : base("launchdarkly:index/viewLinks:ViewLinks", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/lbrlabs",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ViewLinks resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ViewLinks Get(string name, Input<string> id, ViewLinksState? state = null, CustomResourceOptions? options = null)
        {
            return new ViewLinks(name, id, state, options);
        }
    }

    public sealed class ViewLinksArgs : global::Pulumi.ResourceArgs
    {
        [Input("flags")]
        private InputList<string>? _flags;

        /// <summary>
        /// A set of feature flag keys to link to the view.
        /// </summary>
        public InputList<string> Flags
        {
            get => _flags ?? (_flags = new InputList<string>());
            set => _flags = value;
        }

        /// <summary>
        /// The project key. A change in this field will force the destruction of the existing resource and the creation of a new one.
        /// </summary>
        [Input("projectKey", required: true)]
        public Input<string> ProjectKey { get; set; } = null!;

        [Input("segments")]
        private InputList<Inputs.ViewLinksSegmentArgs>? _segments;

        /// <summary>
        /// A set of segments to link to the view. Each segment is identified by its environment ID and segment key.
        /// </summary>
        public InputList<Inputs.ViewLinksSegmentArgs> Segments
        {
            get => _segments ?? (_segments = new InputList<Inputs.ViewLinksSegmentArgs>());
            set => _segments = value;
        }

        /// <summary>
        /// The view key to link resources to. A change in this field will force the destruction of the existing resource and the creation of a new one.
        /// </summary>
        [Input("viewKey", required: true)]
        public Input<string> ViewKey { get; set; } = null!;

        public ViewLinksArgs()
        {
        }
        public static new ViewLinksArgs Empty => new ViewLinksArgs();
    }

    public sealed class ViewLinksState : global::Pulumi.ResourceArgs
    {
        [Input("flags")]
        private InputList<string>? _flags;

        /// <summary>
        /// A set of feature flag keys to link to the view.
        /// </summary>
        public InputList<string> Flags
        {
            get => _flags ?? (_flags = new InputList<string>());
            set => _flags = value;
        }

        /// <summary>
        /// The project key. A change in this field will force the destruction of the existing resource and the creation of a new one.
        /// </summary>
        [Input("projectKey")]
        public Input<string>? ProjectKey { get; set; }

        [Input("segments")]
        private InputList<Inputs.ViewLinksSegmentGetArgs>? _segments;

        /// <summary>
        /// A set of segments to link to the view. Each segment is identified by its environment ID and segment key.
        /// </summary>
        public InputList<Inputs.ViewLinksSegmentGetArgs> Segments
        {
            get => _segments ?? (_segments = new InputList<Inputs.ViewLinksSegmentGetArgs>());
            set => _segments = value;
        }

        /// <summary>
        /// The view key to link resources to. A change in this field will force the destruction of the existing resource and the creation of a new one.
        /// </summary>
        [Input("viewKey")]
        public Input<string>? ViewKey { get; set; }

        public ViewLinksState()
        {
        }
        public static new ViewLinksState Empty => new ViewLinksState();
    }
}
